import React, {useState, useRef} from 'react';
import {useTraining} from '../../context/TrainingContext';
import {bayHazards} from '../../data/hazardsData';
const scenes = [
 {name:'Receiving bay',items:[0,4], symbol:'▱', detail:'Inspect the walkway before moving a load.'},
 {name:'Emergency exit',items:[1],symbol:'EXIT →', detail:'Keep the escape route available.'},
 {name:'Storage racks',items:[2,5],symbol:'▦', detail:'Check load stability and task protection.'},
 {name:'Vehicle crossing',items:[3],symbol:'↔', detail:'Look around before crossing vehicle routes.'}
];
export default function ActivityHazardSpotting(){
 const {foundHazards,registerHazardFound,setActiveHazardModal,activeHazardModal,setCurrentView}=useTraining();
 const [yaw,setYaw]=useState(0), [pitch,setPitch]=useState(0), [list,setList]=useState(false);
 const drag=useRef(null); const degrees=((yaw%360)+360)%360;
 const turn=(v)=>setYaw(y=>y+v);
 return <div className="learning-page"><div className="section-heading"><div><span className="eyebrow">01 / Warehouse orientation</span><h1>Look around. Spot the risk.</h1><p>Explore a simulated 360° warehouse. Inspect all six hotspots before lifting practice.</p></div><strong>{foundHazards.length} / 6 inspected</strong></div>
 <div className="scene-toolbar"><button onClick={()=>turn(-45)}>← Look left</button><span aria-live="polite">Heading {Math.round(degrees)}°</span><button onClick={()=>turn(45)}>Look right →</button><button onClick={()=>{setYaw(0);setPitch(0)}}>Reset view</button><button aria-pressed={list} onClick={()=>setList(!list)}>{list?'Show 360° view':'Accessible list view'}</button></div>
 {!list ? <div className="warehouse-viewport" tabIndex={0} aria-label="360 degree warehouse. Drag to look around or use arrow keys. Hotspots are also available in list view."
 onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')turn(-15);if(e.key==='ArrowRight')turn(15);if(e.key==='ArrowUp')setPitch(p=>Math.min(20,p+5));if(e.key==='ArrowDown')setPitch(p=>Math.max(-20,p-5));}}
 onPointerDown={e=>{if(e.target.closest('button'))return;drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}}
 onPointerMove={e=>{if(!drag.current)return;setYaw(y=>y-(e.clientX-drag.current.x)*.25);setPitch(p=>Math.max(-20,Math.min(20,p+(e.clientY-drag.current.y)*.12)));drag.current={x:e.clientX,y:e.clientY}}}
 onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <div className="warehouse-camera" style={{transform:`translateZ(480px) rotateX(${pitch}deg) rotateY(${yaw}deg)`}}>
 {scenes.map((s,i)=><div className="warehouse-wall" key={s.name} style={{transform:`rotateY(${i*90}deg) translateZ(-480px)`}}><div className="warehouse-sign">BAY {i+1} · {s.name}</div><div className="warehouse-shelves">{[0,1,2].map(j=><div className="rack" key={j}>{[0,1,2,3,4,5].map(k=><span key={k} className="crate"/>)}</div>)}</div><div className="warehouse-landmark" aria-hidden="true">{i===0?<svg viewBox="0 0 320 85"><ellipse cx="90" cy="65" rx="65" ry="17" fill="#5c7380"/><path d="M190 75 Q150 10 240 30 T300 75" fill="none" stroke="#b84338" strokeWidth="8"/><path d="M140 70 L165 15 L190 70Z" fill="#efb441"/></svg>:i===1?<svg viewBox="0 0 320 85"><rect x="100" y="0" width="95" height="80" fill="#227a69"/><text x="109" y="26" fill="white" fontSize="20">EXIT →</text><rect x="110" y="50" width="140" height="35" fill="#c08d54"/><path d="M105 48h150" stroke="#905c32" strokeWidth="7"/></svg>:i===2?<svg viewBox="0 0 320 85"><g transform="rotate(12 100 80)"><rect x="50" y="50" width="90" height="32" fill="#b88753"/><rect x="65" y="20" width="90" height="32" fill="#c79d66"/><rect x="83" y="-10" width="90" height="32" fill="#d6b07d"/></g><circle cx="245" cy="16" r="12" fill="#d6aa86"/><path d="M245 31v32m0-18l-25 12m25-12l22 10m-22 8l-15 22m15-22l15 22" stroke="#526575" strokeWidth="12"/></svg>:<svg viewBox="0 0 320 85"><rect x="80" y="30" width="120" height="40" rx="6" fill="#e7af36"/><path d="M120 30V5h60v55m22-50v65h70" fill="none" stroke="#405766" strokeWidth="8"/><circle cx="110" cy="72" r="13" fill="#405766"/><circle cx="183" cy="72" r="13" fill="#405766"/><path d="M22 37h42m-30 15h30" stroke="#b95b42" strokeWidth="6"/></svg>}</div><div className="hotspot-row">{s.items.map(idx=>{const h=bayHazards[idx];return <button key={h.id} className={`scene-hotspot ${foundHazards.includes(h.id)?'found':''}`} onClick={()=>registerHazardFound(h)} aria-label={`Inspect ${h.name}`}>{foundHazards.includes(h.id)?'✓':'+'} {h.name}</button>})}</div><p>{s.detail}</p></div>)}
 <div className="warehouse-floor"/><div className="warehouse-ceiling"/></div><div className="scene-caption">Drag to look around · Arrow keys supported · Illustrative warehouse</div></div> : <div className="tutorial-grid">{bayHazards.map(h=><button className="learning-card text-left" key={h.id} onClick={()=>registerHazardFound(h)}><strong>{foundHazards.includes(h.id)?'✓ ':''}{h.name}</strong><p>{h.zone}</p><span>Inspect hazard →</span></button>)}</div>}
 <div className="learning-card mt-6"><h2>Your inspection checklist</h2><div className="checklist">{bayHazards.map(h=><span key={h.id}>{foundHazards.includes(h.id)?'✓':'○'} {h.name}</span>)}</div><button className="primary" disabled={foundHazards.length<6} onClick={()=>setCurrentView('manual-handling')}>Continue to guided lifting →</button></div>
 {activeHazardModal&&<div className="dialog-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="hazard-title" className="learning-dialog"><span className="eyebrow">Hazard identified</span><h2 id="hazard-title">{activeHazardModal.name}</h2><p>{activeHazardModal.description}</p><div className="feedback"><strong>Make it safe</strong><p>{activeHazardModal.correctAction}</p></div><button autoFocus className="primary" onClick={()=>setActiveHazardModal(null)}>Acknowledge and continue</button></section></div>}
 </div>
}
