import React,{useState} from 'react';
import {useTraining} from '../../context/TrainingContext';
const steps=[
 {title:'Plan the task',instruction:'Inspect the load, destination and route. Consider whether a handling aid can avoid the lift.',options:['Lift it quickly to test the weight','Assess the task and choose a suitable aid or help','Assume all boxes are the same weight'],correct:1,feedback:'Assess the task, your capability, the load and surroundings before handling. An unknown or awkward load needs assessment, not a trial lift.'},
 {title:'Prepare your position',instruction:'For this assessed, manageable practice box, move close and establish a stable stance.',options:['Keep feet together and reach forward','Stand far away and pull with your back','Move close, feet apart, with one foot slightly forward'],correct:2,feedback:'A stable stance and a close load reduce reaching. Do not start from an unstable or stretched position.'},
 {title:'Secure and lift',instruction:'Use a secure hold and a controlled movement; keep the load near your waist.',options:['Use a secure grip and lift smoothly without further back flexion','Jerk the load upwards','Hold the box at arm’s length'],correct:0,feedback:'Keep the load close and move smoothly. Snatching or reaching increases the difficulty of controlling it.'},
 {title:'Carry and turn',instruction:'Keep a clear view and move along the checked route.',options:['Twist your back while your feet stay still','Turn by moving your feet, keeping the load close','Carry the box above your head'],correct:1,feedback:'Move your feet to turn. Avoid twisting your torso or carrying a load that blocks your view.'},
 {title:'Lower and position',instruction:'The stable destination is ready. Finish the movement under control.',options:['Drop the box onto the stack','Balance it on an uneven edge','Lower smoothly, put it down, then adjust its position'],correct:2,feedback:'Set the load down securely before adjusting it. Keep hands clear of pinch points and leave the stack stable.'}
];
export default function ManualHandling(){
 const {finishPractice,setCurrentView,foundHazards}=useTraining();
 const [stage,setStage]=useState(0),[mode,setMode]=useState('guide'),[feedback,setFeedback]=useState(null),[done,setDone]=useState(false);
 const s=steps[stage];
 if(foundHazards.length<6)return <div className="learning-page"><h1>Inspect your workspace first</h1><p>Find all six hazards in the warehouse orientation, then practise the lifting sequence.</p><button className="primary" onClick={()=>setCurrentView('activity-hazard')}>Open 360° warehouse</button></div>;
 return <div className="learning-page"><span className="eyebrow">02 / Guided manual handling</span><h1>A safer lift, step by step.</h1><p>Practice scenario: an assessed, manageable box moved to a stable waist-height surface. Use your site’s risk assessment for real tasks.</p><div className="step-track">{steps.map((s,i)=><span className={i===stage?'active':''} key={s.title}>{i+1}. {s.title}</span>)}</div>
 {done?<section className="learning-card"><span className="eyebrow">Practice complete</span><h2>You completed all five actions.</h2><p>Take the assessment next. Each submitted attempt is saved with its score and time.</p><button className="primary" onClick={()=>setCurrentView('quiz')}>Start assessment →</button><button onClick={()=>{setDone(false);setStage(0);setMode('guide');setFeedback(null)}}>Review the guide</button></section>:<div className="practice-layout"><div className="lifting-illustration"><svg viewBox="0 0 360 280" role="img" aria-label={`Lifting demonstration: ${s.title}`}><rect x="15" y="240" width="330" height="12" rx="6" fill="#cbd5e1"/><rect x="230" y="160" width="90" height="80" fill="#a5b4fc"/><circle cx="155" cy={stage===2?65:80} r="23" fill="#f2c7a5"/><path d="M155 108 L142 163 L115 200 L100 240 M142 163 L172 200 L185 240 M155 118 L190 151 L222 157" fill="none" stroke="#0f766e" strokeWidth="18" strokeLinecap="round"/><rect x="199" y={stage===4?122:145} width="57" height="42" rx="4" fill="#d6a66c"/><path d="M225 147v37" stroke="#926b3a" strokeWidth="3"/><text x="25" y="35" fill="#0f766e" fontSize="17" fontWeight="bold">{stage+1} / 5 · {s.title}</text></svg><p>{s.instruction}</p></div><section className="learning-card"><span className="eyebrow">{mode==='guide'?'Guided demonstration':'Your turn'}</span><h2>{s.title}</h2>{mode==='guide'?<><p>{s.instruction}</p><div className="feedback">{s.feedback}</div><button className="primary" onClick={()=>{if(stage<4)setStage(stage+1);else{setStage(0);setMode('practice')}}}>{stage<4?'Next demonstration step →':'Try the lifting sequence →'}</button></>:<><p>Choose the safe action for this stage.</p><div className="choice-list">{s.options.map((o,i)=><button key={o} disabled={feedback?.correct} onClick={()=>setFeedback({correct:i===s.correct,text:i===s.correct?'Correct. '+s.instruction:s.feedback})}>{o}</button>)}</div>{feedback&&<div role="status" className={`feedback ${feedback.correct?'':'incorrect'}`}>{feedback.text}</div>}{feedback?.correct&&<button className="primary" onClick={()=>{setFeedback(null);if(stage<4)setStage(stage+1);else{finishPractice();setDone(true)}}}>{stage<4?'Continue →':'Complete practice'}</button>}</>}</section></div>}
 <p className="source-note">Reference: <a href="https://www.hse.gov.uk/msd/manual-handling/good-handling-technique.htm" target="_blank" rel="noreferrer">HSE good handling technique</a>. Handling aids and task improvements take priority over technique alone.</p></div>
}
